apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: validator-role
rules:
# TODO: need update with more strict rules
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
