# the following config is for teaching kustomize where to look at when substituting vars.
# It requires kustomize v2.1.0 or newer to work properly.
nameReference:
- kind: ServiceAccount
  version: v1
  fieldSpecs:
  - kind: Deployment
    group: apps
    path: spec/template/spec/serviceAccountName
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: Deployment
    group: apps
    path: spec/template/spec/volumes/secret/secretName
  

namespace:
- kind: Namespace
  version: v1
  path: metadata/namespace
  create: true